name: Version Increment

on:
  pull_request:
    branches:
      - main

jobs:
  version-increment:
    runs-on: ubuntu-latest
    if: | 
      contains(${{ env.PR_TITLE }}, ${{ env.BREAKING_CHANGE_TAG }}) || 
      contains(${{ env.PR_TITLE }},, ${{ env.FEATURE_TAG }}) || 
      contains(${{ env.PR_TITLE }},, ${{ env.BUGFIX_TAG }})

    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      BREAKING_CHANGE_TAG: "[breaking change]"
      FEATURE_TAG: "[feature]"
      BUGFIX_TAG: "[bugfix]"
      SPLITSCALE_BOT_PAT: ${{ secrets.SPLITSCALE_BOT_PAT }}
      BOT_SSH: ${{ secrets.BOT_SSH }}
      MAJOR_UPDATE: ${{ env.PR_TITLE =~ env.BREAKING_CHANGE_TAG }}
      MINOR_UPDATE: ${{ env.PR_TITLE =~ env.FEATURE_TAG }}
      PATCH_UPDATE: ${{ env.PR_TITLE =~ env.BUGFIX_TAG }}
    
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          token: ${{ env.SPLITSCALE_BOT_PAT }}
          ssh-key: ${{ env.BOT_SSH }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Determine Version Type
        id: version-type
        run: |
          if [[ $MAJOR_UPDATE == true ]]; then
            echo "major"
          elif [[ $MINOR_UPDATE == true ]]; then
            echo "minor"
          elif [[ $PATCH_UPDATE == true ]]; then
            echo "patch"
          fi
        env:
          VERSION_TYPE: ${{ steps.version-type.outputs.stdout }}

      - name: Increment Version
        run: |
          chmod +x .ci/update_version.sh     
          bash .ci/update_version.sh $VERSION_TYPE -p "$GITHUB_WORKSPACE/package.json"
          
      - name: Set Committer Identity
        run: |
          git config --global user.name "${{ vars.BOT_USERNAME }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: Create version tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag v$VERSION

      - name: Stage and Commit Changes
        run: |
          git add --all
          git commit -m "Version bumped to v${{ env.VERSION }} [skip actions]"

      - name: Push changes to branch
        run: |
          git push --follow-tags
