name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SPLITSCALE_BOT_PAT }}
      - run: git config user.email "$BOT_EMAIL"
      - run: git config user.name "$BOT_USERNAME"
      - run: npm version minor -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION} -m "Automated Change [skip actions]"
      - run: git push origin --follow-tags
