name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      SPLITSCALE_BOT_PAT: ${{ secrets.SPLITSCALE_BOT_PAT }}
      
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3

      - name: Update version
        run: |
          chmod +x ./update_version.sh       
          bash ./update_version.sh minor   

      - name: Create version tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag $VERSION -m "Automated Change [skip actions]"

      - name: Pushing to the protected branch 'protected'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ env.SPLITSCALE_BOT_PAT }}
          branch: main
          unprotect_reviews: true
          tags: true
