name: Version Increment

on:
  pull_request:
    branches:
      - main

jobs:
  version-increment:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.title, '[break]') || contains(github.event.pull_request.title, '[feat]') || contains(github.event.pull_request.title, '[fix]')"

    env:
      SPLITSCALE_BOT_PAT: ${{ secrets.SPLITSCALE_BOT_PAT }}
      BOT_SSH: ${{ secrets.BOT_SSH }}
    
    strategy:
      matrix:
        increment-type: [major, minor, patch]
    
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          token: ${{ env.SPLITSCALE_BOT_PAT }}
          ssh-key: ${{ env.BOT_SSH }}
    
      - name: Determine version increment type
        id: increment-type
        run: |
          echo "::set-output name=increment-type::$(echo ${{ github.event.pull_request.title }} | sed -E 's/.*\[break\].*/major/;s/.*\[feat\].*/minor/;s/.*\[fix\].*/patch/')"
    
      - name: Update version
        if: steps.increment-type.outputs.increment-type
        run: |
          chmod +x .ci/update_version.sh     
          bash .ci/update_version.sh ${{ steps.increment-type.outputs.increment-type }} -p "$GITHUB_WORKSPACE/package.json"
          
      - name: Set Committer Identity
        if: steps.increment-type.outputs.increment-type
        run: |
          git config --global user.name "${{ vars.BOT_USERNAME }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: Create version tag
        if: steps.increment-type.outputs.increment-type
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag v${{ env.VERSION }}

      - name: Stage and Commit Changes
        if: steps.increment-type.outputs.increment-type
        run: |
          git add --all
          git commit -m "Version bumped to v${{ env.VERSION }} [skip actions]"

      - name: Push changes to branch
        if: steps.increment-type.outputs.increment-type
        run: |
          git push origin ${{ github.head_ref }} --tags --force
