name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      SPLITSCALE_BOT_PAT: ${{ secrets.SPLITSCALE_BOT_PAT }}
      
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3

      - name: Update version
        run: |
          chmod +x ./update_version.sh       
          bash ./update_version.sh minor
          
      - name: Set Committer Identity
        run: |
          git config --global user.name "${{ vars.BOT_USERNAME }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: Set Remote URL
        run: |
          git remote set-url origin https://${{ env.SPLITSCALE_BOT_PAT }}@github.com/splitscale/arrow

      - name: Create version tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag $VERSION -m "Automated Change [skip actions]"

      - name: Git Status
        run: git status

      - name: Stage and Commit Changes
        run: |
          git add --all
          git commit -m "Automated commit [skip actions]"

      - name: Pushing to the protected branch 'main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ env.SPLITSCALE_BOT_PAT }}
          branch: main
          unprotect_reviews: false
          tags: true
