name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SPLITSCALE_BOT_PAT: ${{ secrets.SPLITSCALE_BOT_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global URL.https://${{ env.SPLITSCALE_BOT_PAT }}@github.com/.insteadOf ssh://git@github.com/
          
      - run: git config --global user.name "${{ env.BOT_USERNAME }}"
      - run: git config --global user.email "${{ env.BOT_EMAIL }}"
      
      - run: npm version minor -m "v%s"
      - run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - run: git tag ${{ env.VERSION }} -m "Automated Change [skip actions]"
      - run: git push origin --follow-tags
