name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global URL."https://${{vars.BOT_USERNAME}}:${{ secrets.SPLITSCALE_BOT_PAT }}@github.com/".insteadOf ssh://git@github.com/
          
      - run: git config --global user.name "${{vars.BOT_USERNAME}}"
      - run: git config --global user.email "${{vars.BOT_EMAIL}}"
      
      - run: npm version minor -m "v%s"
      - run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - run: git tag ${{ env.VERSION }} -m "Automated Change [skip actions]"
      - run: git push origin --follow-tags
